#include "sounds.h"

#define LENGTH_OF_TONE 70

struct tone mario[33] = {
	{D, LENGTH_OF_TONE},
	{C, LENGTH_OF_TONE},
	{B, LENGTH_OF_TONE},
	{D, LENGTH_OF_TONE},
	{C, LENGTH_OF_TONE},
	{B, LENGTH_OF_TONE},
	{D, LENGTH_OF_TONE},
	{D, LENGTH_OF_TONE},
	{D, LENGTH_OF_TONE},
	{A, LENGTH_OF_TONE},
	{E, LENGTH_OF_TONE},
	{D, LENGTH_OF_TONE},
	{C, LENGTH_OF_TONE},
	{E, LENGTH_OF_TONE},
	{D, LENGTH_OF_TONE},
	{C, LENGTH_OF_TONE},
	{E, LENGTH_OF_TONE},
	{E, LENGTH_OF_TONE},
	{E, LENGTH_OF_TONE},
	{E, LENGTH_OF_TONE},
	{F, LENGTH_OF_TONE},
	{E, LENGTH_OF_TONE},
	{D, LENGTH_OF_TONE},
	{F, LENGTH_OF_TONE},
	{E, LENGTH_OF_TONE},
	{D, LENGTH_OF_TONE},
	{F, LENGTH_OF_TONE},
	{F, LENGTH_OF_TONE},
	{F, LENGTH_OF_TONE},
	{G, LENGTH_OF_TONE},
	{G, LENGTH_OF_TONE},
	{H, LENGTH_OF_TONE},
	{H, LENGTH_OF_TONE},
};

struct tone hit[37] = {
	{A, 10},
	{B, 10},
	{C, 10},
	{D, 10},
	{E, 10},
	{F, 10},
	{F, 10},
	{E, 10},
	{D, 10},
	{C, 10},
	{B, 10},
	{A, 10},
	{A, 10},
	{B, 10},
	{C, 10},
	{D, 10},
	{E, 10},
	{F, 10},
	{F, 10},
	{E, 10},
	{D, 10},
	{C, 10},
	{B, 10},
	{A, 10},
	{A, 10},
	{B, 10},
	{C, 10},
	{D, 10},
	{E, 10},
	{F, 10},
	{F, 10},
	{E, 10},
	{D, 10},
	{C, 10},
	{B, 10},
	{A, 10},
	{SILENCE, 10000000}
};

